mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView

app_name = 'mysite'

urlpatterns = [
    path('', RedirectView.as_view(url='user/')),
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('user/', include('user.urls')),
    path('admindash/', include('adminDash.urls')),
]

user/urls.py
from django.urls import include, path

from . import views

app_name = 'user'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.passwordless_login, name='register'),
    path('login/', views.passwordless_login, name='login'),
    path('home/', views.home, name='home'),
    path('visit/', views.log_visit, name='visit'),
    path('visit/<str:otp>/success/', views.visit_success, name='visit_success'),
    path('directions/', views.directions, name='directions'),
    path('logout/', views.signout, name='logout'),
    path('verification/', views.verify_email, name='verify'),
    path('instructions/', views.instructions, name='instructions'),
    path('welcome/', views.welcome, name='welcome'),
    path('consent/', views.consent, name='consent'),
    path('reset/', views.reset_pwd, name='reset'),
    path('ishihara/', views.ishihara, name='ishihara'), 
    path('screen/', views.screen, name='screen'),
    path('freescreen/', views.freescreen, name='freescreen'),
    path('msg/', views.error, name='error'),
    path('getname/', views.forgot_username, name='forgot_username'),
    path('continue/', views.long_proposal, name='long_proposal'),
    path('complete/', views.session_complete, name='session_complete'),
    # path('verification/', include('verify_email.urls')),
    # path('login/', views.login, name='login'),
    # path('logout/', views.vote, name='logout')
]

# urlpatterns = [
#     path('', views.IndexView.as_view(), name='index'),
#     path('<int:pk>/', views.DetailView.as_view(), name='detail'),
#     path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
#     path('<int:question_id>/vote/', views.vote, name='vote'),
# ]

user/models.py
import datetime
from email.policy import default

from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class participant(models.Model):
    def __str__(self):
        return self.user.username + ": " + self.user.email
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    visit_time_1 = models.DateTimeField(default=datetime.datetime(1000,1,1,0,0,0))
    visit_time_2 = models.DateTimeField(default=datetime.datetime(1000,1,1,0,0,0))
    visit_time_3 = models.DateTimeField(default=datetime.datetime(1000,1,1,0,0,0))
    visit_time_4 = models.DateTimeField(default=datetime.datetime(1000,1,1,0,0,0))
    visit_time_5 = models.DateTimeField(default=datetime.datetime(1000,1,1,0,0,0))
    visit_time_6 = models.DateTimeField(default=datetime.datetime(1000,1,1,0,0,0))
    last_visit = models.DateTimeField(default=datetime.datetime(1000,1,1,0,0,0))
    last_email = models.DateTimeField(default=datetime.datetime(1000,1,1,0,0,0))
    sessions_completed = models.IntegerField(default=0)
    is_verified = models.BooleanField(default=False)
    is_eligible = models.IntegerField(default=0) # 0 = not screened, 1 = eligible, 2 = ineligible
    is_colorBlind = models.BooleanField(default=True)
    is_colorTested = models.BooleanField(default=False)
    longitudinal_enrollment_status = models.IntegerField(default=0) # 0 = unproposed, 1 = opt in, 2 = opt out
    ref = models.CharField(default='noref', max_length=30)
    # cloudresearch_aid = models.CharField(default='', max_length=30)

class waitlist(models.Model):
    def __str__(self) -> str:
        return self.user.username
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    age = models.IntegerField(default=0)
    covid_history = models.BooleanField(default=False)

class screen_profile(models.Model):
    def __str__(self) -> str:
        return self.user.username
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    age = models.BooleanField(default=False)
    english = models.BooleanField(default=False)
    covid_testPositive = models.BooleanField(default=False)
    covid_symptoms = models.BooleanField(default=False)

class codes(models.Model):
    def __str__(self):
        return str(self.otp)
        # return str(self.otp) + "; " + str(self.session_num) + "; " + str(self.is_paid)
    otp = models.CharField(max_length=12)
    session_num = models.IntegerField(default=0)
    is_paid = models.BooleanField(default=False)
    is_complete = models.BooleanField(default=False)
    ref = models.CharField(default='noref', max_length=30)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        long_enroll = 0 if settings.USER_LONGITUDINAL_OPT_IN is True else 1
        participant.objects.create(user=instance, longitudinal_enrollment_status=long_enroll)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    if instance.is_superuser == 0: 
        instance.participant.save()

user/views.py
import datetime
import functools
import json
import os
from dataclasses import dataclass
from email.policy import default
from logging import exception
from random import shuffle
from sqlite3 import IntegrityError, OperationalError
from urllib.parse import parse_qs, urlencode

import environ
import pytz
import shortuuid
from django.conf import settings
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.signals import user_login_failed
from django.core.mail import send_mail
from django.db import IntegrityError, OperationalError
from django.dispatch import receiver
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils import timezone
from django.views import generic
from verify_email.email_handler import send_verification_email

from configSolo.models import SiteConfiguration
from user.models import codes, participant, screen_profile, waitlist

try:
    SiteConfiguration.objects.create()
except IntegrityError:
    pass
except Exception as e:
    print(f"Error creating SiteConfiguration: {e}")

env = environ.Env()
MAX_SESSIONS = settings.USER_MAX_SESSIONS
SESSION_INTERVAL_DAYS = settings.USER_SESSION_INTERVAL_DAYS
SESSION_INTERVAL_DAYS_MAX = settings.USER_SESSION_INTERVAL_DAYS_MAX
SESSION_LINKS = settings.USER_SESSION_LINKS
SESSION_AMOUNTS = settings.USER_SESSION_AMOUNTS
SCREEN_FAIL_REDIRECT = settings.USER_SCREEN_FAIL_REDIRECT
QUOTA_FULL_REDIRECT = settings.USER_QUOTA_FULL_REDIRECT
SESSION_COMPLETE_REDIRECT = settings.USER_SESSION_COMPLETE_REDIRECT
LONGITUDINAL_DISABLED = settings.USER_LONGITUDINAL_DISABLED
COLLECT_EMAILS = settings.USER_COLLECT_EMAILS

def get_url(base_url, **kwargs):
    """
    f"{base_url}?{urlencode(params)}"
    """
    return f"{base_url}?{urlencode(kwargs)}"

def credirect(base_url, **kwargs):
    params = urlencode(kwargs)
    return redirect(f"{base_url}?{params}")

def long_or_single(func):
    @functools.wraps(func)
    def wrapper(request, template_path, *args, **kwargs):
        if request.user.is_authenticated is False or request.user.participant.longitudinal_enrollment_status != 1:
            tsplit = template_path.split('.')
            try:
                template_path = tsplit[0] + '_single.' + tsplit[1]
            except:
                pass
        return func(request, template_path, *args, **kwargs)
    return wrapper

crender = long_or_single(render)
"""
django.shortcuts.render with longitudinal enrollment status check. \\
Renders the appropriate template based on the user's longitudinal enrollment status. \\
Current logic is that if the user is not enrolled in the longitudinal study, the template is suffixed with '_single'.
"""


def index(request):
    return redirect('user:home')

def instructions(request):
    return crender(request, 'user/instructions.html')

def welcome(request):
    if request.method == "GET":
        ref = request.GET.get('ref', '')
        if ref == '':
            ref = 'noref'
        request.session['ref'] = ref

    elif request.method == "POST":
        try:
            entered_email = request.POST['email']
        except:
            return HttpResponse("There was an issue processing the entered email. Are you sure you entered correctly?" + '<a href="/user/welcome"}>Try again.</a>')
        else: 
            try:
                ref = request.session['ref']
            except KeyError:
                ref = 'err'
            msg_greet = "Hi " + entered_email.split('@')[0] + "! <br><br> Thank you for showing an interest in our research. You have received this email because you opted for it on our welcome page. To know more about the study, simply click the link below. "
            msg_link = f"Here is the link to participate in the study: {SiteConfiguration.objects.get().site_url}/user/welcome/?ref={ref}"
            msg_req = "Please note that the study requires you to have a laptop/desktop with a physical keyboard. iPads will not work."
            auto_note = '<br><br>Note that this is an automated email message. Please do not reply.'
            send_mail('[Indian Mental Wellbeing Study] Link for participation',
                '',
                str(env('SMTP_MAIL')),
                [entered_email],
                html_message=msg_greet + "<br>" + msg_link + "<br><br>" + msg_req + "<br><br>" + auto_note,
                fail_silently=True)
                
    return crender(request, 'user/welcome.html')

def consent(request):
    return crender(request, 'user/consent.html')

def user_init(user):
    user.participant.sessions_completed = 0
    user.save()

def user_new_visit(user, ref):
    user.participant.sessions_completed += 1
    t = timezone.now()
    user.participant.last_visit = t
    ob = codes.objects.create(otp=shortuuid.ShortUUID().random(length=12), session_num=user.participant.sessions_completed, ref=ref)
    if (user.participant.sessions_completed==1):
        user.participant.visit_time_1 = t
    elif (user.participant.sessions_completed==2):
        user.participant.visit_time_2 = t
    elif (user.participant.sessions_completed==3):
        user.participant.visit_time_3 = t
    elif (user.participant.sessions_completed==4):
        user.participant.visit_time_4 = t
    elif (user.participant.sessions_completed==5):
        user.participant.visit_time_5 = t
    elif (user.participant.sessions_completed==6):
        user.participant.visit_time_6 = t
    else:
        return HttpResponse("Something went wrong.")
    user.save()
    return ob.otp

def verify_email(request):
    try:
        entered_code = request.POST['code']
    except:
        return render(request, 'user/verification.html', context={'left': request.session['attempts_left']})
    else:
        user = get_object_or_404(User, username=request.session['verif_user'])
        if user.is_active is False:
            return redirect(f"{reverse('user:error')}?err=completion-success")
        if(request.session['verif_code'] == entered_code):
            user.participant.is_verified = True
            user.participant.ref = request.session.pop('ref', 'noKey')
            # user.participant.cloudresearch_aid = request.session.pop('cloudAid', 'noKey')
            user.save()
            del request.session['verif_user'], request.session['verif_code'], request.session['attempts_left']
            login(request, user=user)
            return redirect(f"{reverse('user:error')}?err=verif-success")
        else:
            if(request.session['attempts_left'] > 1):
                request.session['attempts_left'] -= 1
                return render(request, 'user/verification.html', context={'left': request.session['attempts_left']})
            else:
                del request.session['verif_user'], request.session['verif_code'], request.session['attempts_left']
                user.delete()
                return redirect(f"{reverse('user:error')}?err=verif-too-many")

def register(request):
    # cloudAid = ''
    # if request.method == "GET":
    #     cloudAid = request.GET.get('aid', None)
    #     # if not 'cloudAid' in request.session or request.session['cloudAid'] == '' or request.session['cloudAid'] == 'noKey':
    #     if cloudAid is not None:
    #         request.session['cloudAid'] = cloudAid
    #     # aid = request.GET.get('aid', '')
    #     # request.user.participant.cloudresearch_aid = aid
    #     # request.user.save()

    try:
        entered_username = request.POST['username']
        if COLLECT_EMAILS is True:
            entered_email = request.POST['email']
        entered_pwd = request.POST['password']
        entered_pwd_again = request.POST['password-again']
        entered_age = request.POST['age']
        # user = User.objects.create_user(entered_username, entered_email, entered_pwd)
    except:
        return render(request, 'user/registration.html', context={'err_msg': ''})
    else:
        # * Check if passwords match
        if entered_pwd != entered_pwd_again:
            return render(request, 'user/registration.html', context={'err_msg': "Passwords do not match."})
        
        # * Check if age is above cutoff
        # if(int(entered_age)<int(env('AGE_CUTOFF'))):
        if(int(entered_age) < 18):
            return render(request, 'user/registration.html', context={'err_msg': "Sorry, you must be at least " + env('AGE_CUTOFF') + " years old to continue."})

        # * Check if cloudAid already exists
        # cloudAid = request.session.get('cloudAid', 'noKey')
        # if cloudAid != 'noKey':
        #     count_existing = User.objects.filter(participant__cloudresearch_aid=request.session['cloudAid']).count()
        #     if(count_existing > 0):
        #         return render(request, 'user/registration.html', context={'err_msg': 'That cloudAid already exists! Please visit the link via CloudResearch.'})
        # else:
        #     return render(request, 'user/registration.html', context={'err_msg': 'Please visit the link via CloudResearch.'})
        
        # * Check if email already exists
        if COLLECT_EMAILS is True:
            count_existing = User.objects.filter(email=entered_email).count()
            try:
                allowed_emails = env('ALLOWED_EMAILS').split(',')
            except:
                allowed_emails = []
                print("Error reading ALLOWED_EMAILS from .env file.")
            if(count_existing > 0 and entered_email not in allowed_emails):
                return render(request, 'user/registration.html', context={'err_msg': 'That email already exists! If you have already created an account, please log in instead.'})
        

user/templates/user/dashboard_single.html
{% extends 'user/dashboard.html' %}

{% block progress_bar %}
{% endblock %}

{% block next_content %}
<!-- <p>Your CloudResearch AID: {{user.participant.cloudresearch_aid}}</p> -->
<p>Click the button below to proceed.</p>
{% endblock %}

{% block last_visit %}
{% endblock %}

user/templates/user/directions.html
<head>  
    <meta charset="UTF-8">  
    <title>Directions</title>  
    {% load static %}  
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> 
    <!-- <link rel="stylesheet" href="{% static 'home.css' %}"> -->
    <link rel="stylesheet" href="{% static 'dashboard.css' %}">
    <link rel="stylesheet" href="{% static 'nav.css' %}">
    <link rel="stylesheet" href="{% static 'footer.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>  
    <style>
        #r1 .card {
            height: auto;
        }
        .btn {
            width: 400px;
        }
    </style>
</head> 
<body>
<nav class="navbar navbar-dark fixed-top navbar-custom navbar-expand-lg flex-md-nowrap p-1 shadow p-1 mb-5 " >

    <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="{% url 'user:home' %}">Hi, {{ request.user.username }}!</a>
    <div class="navbar-collapse collapse flex-grow-1 text-right"> </div>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'user:instructions' %}">Instructions</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'user:logout' %}">Logout</a>
            </li>
        </ul>
    <!-- <ul class="navbar-nav px-3">
    </ul> -->

</nav>

<main role="main">
    <div class="container">
        <!-- Row 1 -->
        <div class="row justify-content-center" id="r1">
            <div class="card shadow p-3 mb-5 bg-white rounded">
                <h4 class="card-title"> Directions </h4>
                <div class="card-body">
                    <ol>
                        <li>This study requires you to be using a laptop or a desktop. </li>
                        <li>Kindly refrain from using mobiles/tablets/iPads for the study.</li>
                        <li>This study requires you to have <u>a real keyboard</u>.</li>
                        <li>Make sure you are in a quiet environment and free from distractions. This includes music and your mobile phone.</li>
                        <li>You should ideally not participate in the study during the night (or if you are within about four hours of your bedtime).</li>
                        <li>Please sit straight during the course of the study.</li>
                        <li>Adjust the monitor/display so that the top of the screen is at or slightly below eye level.</li>
                        <li>Your eyes should look slightly downward when viewing the middle of the screen.</li>
                        <li>Position the monitor/display from your eyes at about an arm's length distance (at least 20 inches or 51 cm). If your screen is larger, add more viewing distance.</li>
                    </ol>
                    <p> If you are unclear about the instructions, please click the 'Instructions' button on the top right before continuing. </p>
                    <p> If you have understood the above directions, please confirm by clicking the button below to proceed. Once you have confirmed, your attempt will be recorded; so kindly do not hit refresh or back button on your browser.</p>
                    <form action="{% url 'user:visit' %}" method="GET">
                        {% csrf_token %}
                        <!-- <p><b>If you have prescription for your eyesight, please make sure you wear your prescribed glasses/lenses, and you check the box below.<br>
                        By not checking, you convey that you do not have a prescription.</b></p>
                        <label for="wearing">
                            <input type="checkbox" name="wearing" id='wearing'> <u>I am wearing my prescribed glasses/lenses for the study.</u>
                        </label> -->
                        <p><b>If you have prescription for your eyesight, please make sure you wear your prescribed glasses/lenses.<br>Please select the appropriate option below.</b></p>
                        <input type="radio" id="wearing" name="wearing" value=1 required> I have a prescription and I am wearing my prescribed glasses/lenses for the study.</input>
                        <br>
                        <input type="radio" id="notwearing" name="wearing" value=2 required> I do not have a prescription.
                        <div class="text-center">
                            
                            <br><br>
                            <p style="color: red;">Note that clicking the button below will start your session. Be ready.</p>
                            <button type="submit" class="btn btn-primary"> I'm ready, let's start.</button>
                    </div>
                </form>
            </div>
            </div>
        </div>
</main>
</body>
{% include 'user/footer.html' %}

user/templates/user/footer.html
<footer>
    <p>Contact:</p>
    <p><a href="mailto:vivek.pamnani@research.iiit.ac.in">vivek.pamnani@research.iiit.ac.in</a></p>
    <p>(Vivek Pamnani)</p>
</footer>

user/templates/user/index.html
This is the index page.

user/templates/user/passwordless_login.html
<!DOCTYPE html>
<html lang="en" >
<head>
  <!-- <meta charset="UTF-8"> -->
  <meta name="viewport" content="width=device-width, initial-scale=1" charset="UTF-8">
  <title>Indian Mental Wellbeing Study: Welcome back! </title>
  {% load static %}  
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> 
  <link rel="stylesheet" href="{% static 'login.css' %}">
  <link rel="stylesheet" href="{% static 'footer.css' %}">
</head>

<body>
<!-- partial:index.partial.html -->
<section class='login' id='login'>
  <div class='head'>
  <h1 class='company'>Indian Mental Wellbeing Study</h1>
  </div>
  <p class='msg'>Welcome!</p>
  <div class='form'>
    <form action="{% url 'user:login' %}" method="post">
        {% csrf_token %}
        <input type="email" name="email" placeholder='Email' class='text' id='email' autofocus required><br>
        <p style="color: #FF0000;">{% autoescape off %}{{ err_msg }}{% endautoescape %}
        </p>
        <div style="text-align:center;">
            <input class='btn-login' id='do-login' type="submit" value="Login"></input>
        </div>
    </form>
  </div>
</section>
<!-- partial -->

</body>
{% include 'user/footer.html' %}

</html>

user/templates/user/screen.html
<head>  
    <meta name="viewport" content="width=device-width, initial-scale=1" charset="UTF-8">
    <title>Directions</title>  
    {% load static %}  
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> 
    <!-- <link rel="stylesheet" href="{% static 'home.css' %}"> -->
    <link rel="stylesheet" href="{% static 'dashboard.css' %}">
    <link rel="stylesheet" href="{% static 'nav.css' %}">
    <link rel="stylesheet" href="{% static 'footer.css' %}">
    <!-- <script src="{% static 'js/bootstrap.min.js' %}"></script> -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>  
    <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script> -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous" async defer></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous" async defer></script>
    <script src="{% static 'screen.js' %}" async defer></script>
    <!-- <script>
        // $('#myModal').on('shown.bs.modal', function () {
        //     $('#myInput').trigger('focus')
        // })
        console.log("Script loaded");
        function log() {
            console.log("Button clicked");
        }
        $(document).ready(function() {
            $('#dummy-btn').click(function() {
                console.log("Button clicked 1");
            });
            $('#modal-confirm').click(function() {
                console.log("Submitting form.");
                // check if required fields are filled
                $('#exampleModal').on('hidden.bs.modal', function (e) {
                    console.log("Modal closed");
                    $('#screen-submit').click();
                });
            });
        });
    </script> -->
    <style>
        #r1 .card {
            height: auto;
        }
        .btn {
            width: 400px;
        }
    </style>
</head> 

<body>
    
    <nav class="navbar navbar-dark fixed-top navbar-custom navbar-expand-lg flex-md-nowrap p-1 shadow p-1 mb-5 " >

        <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="{% url 'user:home' %}"></a>
        <div class="navbar-collapse collapse flex-grow-1 text-right"> </div>
            <ul class="navbar-nav ml-auto">
                <!-- <li class="nav-item">
                    <a class="nav-link" href="{% url 'user:instructions' %}">Instructions</a>
                </li> -->
                <!-- <li class="nav-item">
                    <a class="nav-link" href="{% url 'user:logout' %}">Logout</a>
                </li> -->
            </ul>
        <!-- <ul class="navbar-nav px-3">
        </ul> -->
    
    </nav>

<main role="main">
    <div class="container">


        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Confirm submission</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure you want to submit your answers?
            </div>
            <div class="modal-footer">
                <button type="button" style="width: 200px;" class="btn btn-secondary btn-modal" data-dismiss="modal">Close</button>
                <button type="button" style="width: 200px;" class="btn btn-primary btn-modal" data-dismiss="modal" id="modal-confirm">Save changes</button>
            </div>
            </div>
        </div>
        </div>

        <div class="row justify-content-center">
            <div class="card shadow p-3 mb-5 bg-white rounded">
                <h4 class="card-title">Screening</h4>
                <p class="class-subtitle">Please answer the following questions to the best of your ability.</p> 
                {% if free is True %}
                    <form action="{% url 'user:freescreen' %}" id="screen-form" method="POST">
                {% else %}
                    <form action="{% url 'user:screen' %}" id="screen-form" method="POST">
                {% endif %}
                {% csrf_token %}
                    <div class="card-body">
                        {% if eligible == 0 %}
                            <table class="table mx-auto" style="width: 70%; min-width: 300px;">
                                <thead>
                                    <tr>
                                        <th scope="col">Question</th>
                                        <th scope="col">Answer</th>
                                    </tr>
                                </thead>
                                <tr>
                                    <td>What is your age?</td>
                                    <td><input type="number" name="age" placeholder='Age' id="age" min="0" max="100" step="1" required></td>
                                </tr>
                                <tr>
                                    <td>Do you speak English?</td>
                                    <td>
                                        <input type="radio" name="english" value=1 required> Yes
                                        <br>
                                        <input type="radio" name="english" value=0 required> No
                                    </td>
                                </tr>
                            <!-- <tr>
                                <td>Have you ever been tested positive for COVID-19?</td>
                                <td>
                                    <input type="radio" name="covid_test" value=1 required> Yes
                                    <br>
                                    <input type="radio" name="covid_test" value=0 required> No
                                </td>
                            </tr> -->
                            <tr>
                                <td>Do you have a history (i.e., diagnosed/tested positive) of any of the listed infections?<br>(Check all that apply)</td>
                                <td>
                                    <table id="inf-table">
                                        <!-- * Can be populated by screen.js too.* -->
                                        {% for infRow in infTable %}
                                            <tr>
                                                {% for inf in infRow %}
                                                    <td>
                                                        <input type="checkbox" name="infHistory" value="{{ inf.0 }}" > {{ inf.1 }}<br>
                                                        <!-- <p>Hello</p> -->
                                                    </td>
                                                {% endfor %}
                                            </tr>
                                        {% endfor %}
                                    </table>
                                </td>
                            </tr>
                            <tr>
                                <td>Have you had or suspect you have had symptoms of COVID-19?</td>
                                <td>
                                    <input type="radio" name="covid_symptoms" value=1 required> Yes
                                    <br>
                                    <input type="radio" name="covid_symptoms" value=0 required> No
                                </td>
                            </tr>
                        </table>
                        {% elif eligible == 2 %}
                            <p>☹️ You do not clear one or more of the following criteria for our study:</p>
                            <ul>
                                <li>Age: 18-60</li>
                                <li>English Speaking</li>
                                <li>Must have tested positive for COVID-19</li>
                                <li>Must have had or suspect you have had symptoms of COVID-19</li>
                            </ul>
                        {% endif %}
                        </div>
                        <div style="text-align:center;">
                            {% if eligible == 2 %}
                                <input class='btn btn-primary' id='sry' value="Sorry, ineligible." style="width: 25%; min-width: 200px; padding: 3px; background-color: #EF4444;"></input>
                            {% else %}
                                <button class="btn btn-primary" id="call-modal" type="button" style="width: 250px; padding: 3px" data-toggle="modal" data-target="#exampleModal">Submit</button>
                                <input class='btn btn-primary' id='screen-submit' type="submit" style="width: 250px; padding: 3px" value="SubmitScreenForm" hidden></input>
                            {% endif %}
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</main> 
<br>
<br>
<br>

</body>
{% include 'user/footer.html' %}
</html>