adminDash/urls.py
from django.urls import include, path

from . import views

app_name = 'adminDash'

urlpatterns = [
    path('', views.adminDash, name='adminDash'),
    path('login/', views.signin, name='login'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView

app_name = 'mysite'

urlpatterns = [
    path('', RedirectView.as_view(url='user/')),
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('user/', include('user.urls')),
    path('admindash/', include('adminDash.urls')),
]

user/urls.py
from django.urls import include, path

from . import views

app_name = 'user'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.passwordless_login, name='register'),
    path('login/', views.passwordless_login, name='login'),
    path('home/', views.home, name='home'),
    path('visit/', views.log_visit, name='visit'),
    path('visit/<str:otp>/success/', views.visit_success, name='visit_success'),
    path('directions/', views.directions, name='directions'),
    path('logout/', views.signout, name='logout'),
    path('verification/', views.verify_email, name='verify'),
    path('instructions/', views.instructions, name='instructions'),
    path('welcome/', views.welcome, name='welcome'),
    path('consent/', views.consent, name='consent'),
    path('reset/', views.reset_pwd, name='reset'),
    path('ishihara/', views.ishihara, name='ishihara'), 
    path('screen/', views.screen, name='screen'),
    path('freescreen/', views.freescreen, name='freescreen'),
    path('msg/', views.error, name='error'),
    path('getname/', views.forgot_username, name='forgot_username'),
    path('continue/', views.long_proposal, name='long_proposal'),
    path('complete/', views.session_complete, name='session_complete'),
    # path('verification/', include('verify_email.urls')),
    # path('login/', views.login, name='login'),
    # path('logout/', views.vote, name='logout')
]

# urlpatterns = [
#     path('', views.IndexView.as_view(), name='index'),
#     path('<int:pk>/', views.DetailView.as_view(), name='detail'),
#     path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
#     path('<int:question_id>/vote/', views.vote, name='vote'),
# ]

adminDash/models.py
from django.db import models

# Create your models here.

adminDash/views.py
import datetime
import functools
import json
from dataclasses import dataclass
from email.policy import default
from logging import exception
from random import shuffle
from sqlite3 import IntegrityError, OperationalError
from urllib.parse import urlencode

import environ
import pytz
import shortuuid
from django.conf import settings
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.signals import user_login_failed
from django.core.mail import send_mail
from django.db import IntegrityError, OperationalError
from django.dispatch import receiver
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils import timezone
from django.views import generic
from verify_email.email_handler import send_verification_email

MAX_SESSIONS = settings.USER_MAX_SESSIONS
SESSION_INTERVAL_DAYS = settings.USER_SESSION_INTERVAL_DAYS
SESSION_INTERVAL_DAYS_MAX = settings.USER_SESSION_INTERVAL_DAYS_MAX
SESSION_LINKS = settings.USER_SESSION_LINKS
SESSION_AMOUNTS = settings.USER_SESSION_AMOUNTS

# Create your views here.
def index(request):
    return HttpResponse("Hello, world. You're at the adminDash index.")
    # return render(request, 'adminDash/index.html')

# ! Unused
def signin(request):
    return redirect('user:login')
    print("adminDash:login")
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            if user.is_superuser != 1:
                return render(request, "adminDash/login.html", {
                    "err_msg": "You are not an admin."
                })
            login(request, user)
            return redirect('adminDash:adminDash')
        else:
            return render(request, "adminDash/login.html", {
                "message": "Invalid credentials."
            })
    else:
        return render(request, "adminDash/login.html")

def adminDash(request):
    if request.user.is_superuser != 1:
        return redirect('adminDash:login')

    users = User.objects.all()
    total_participants = 0

    # * Get session completion counts
    sess_counts = [[0, 100, 100] for _ in range(7)]
    for user in users:
        # ! Superusers/admins will not have a participant object; skip them.
        if user.is_superuser is True:
            continue
        
        user_sessions_completed = user.participant.sessions_completed
        if user_sessions_completed > 0:
            total_participants += 1
        for sessnum in range(user_sessions_completed+1):
            sess_counts[sessnum][0] += 1
    for sessnum in range(1, 7):
        try:
            sess_counts[sessnum][1] = sess_counts[sessnum][0] * 100 // sess_counts[1][0] 
        except:
            sess_counts[sessnum][1] = 0
        try:
            sess_counts[sessnum][2] = sess_counts[sessnum][0] * 100 // sess_counts[sessnum-1][0] if sessnum > 1 else 100
        except:
            sess_counts[sessnum][2] = 0

    # * Get sessions completed last week
    last_week = timezone.now() - datetime.timedelta(days=7)
    last_week_participants = 0
    for user in users:
        # ! Superusers/admins will not have a participant object; skip them.
        if user.is_superuser is True:
            continue
        
        user_sessions_completed = user.participant.sessions_completed
        user_last_visit = user.participant.last_visit
        if user_last_visit > last_week:
            last_week_participants += 1

    # * Get % of participants enrolled for longitudinal study
    longitudinal_accepted = 0
    longitudinal_rejected = 0
    longitudinal_unanswered = 0
    for user in users:
        # ! Superusers/admins will not have a participant object; skip them.
        if user.is_superuser is True:
            continue
        
        user_sessions_completed = user.participant.sessions_completed
        try:
            user_longitudinal = user.participant.longitudinal_enrollment_status
        except:
            user_longitudinal = 0
        if user_sessions_completed > 0:
            if user_longitudinal == 1:
                longitudinal_accepted += 1
            elif user_longitudinal == 2:
                longitudinal_rejected += 1
            else:
                longitudinal_unanswered += 1
    total_proposed = longitudinal_accepted + longitudinal_rejected + longitudinal_unanswered
    longitudinal_acceptance_rate = longitudinal_accepted * 100 // total_proposed

    return render(request, 'adminDash/adminDash.html', {
        'sess_counts': sess_counts[1:],
        'total_participants': total_participants,
        'last_week': last_week_participants,
        'long_acceptance_rate': longitudinal_acceptance_rate,
    })

adminDash/templates/adminDash/adminDash.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load static %}  
    <!-- <link rel="stylesheet" href="{% static 'font_roboto.css' %}"> -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> 
    <!-- <link rel="stylesheet" href="{% static 'dashboard.css' %}"> -->
    <link rel="stylesheet" href="{% static 'nav.css' %}">
    <link rel="stylesheet" href="{% static 'footer.css' %}">
    <style>
        body {
            /* color: #fff; */
            /* background: #E6E6FA; */
            background: #fefafe;
            font-family: 'Roboto', sans-serif;
        }

        .navbar-custom {
            /* background-color: #009688; */
            background: #136a8a;
            background: 
                -webkit-linear-gradient(to right, #267871, #136a8a);
            background: 
                linear-gradient(to right, #267871, #136a8a);
        }

        .btn-primary {
            background-color: #267871;
            /* width: 25%;
            min-width: 200px; */
            /* padding: 3px; */
        }
        .btn-primary:hover {
            background-color: #136a8a;
        }

        img {
            max-width: 100%;
        }

        main {
            padding-top: 80px;
        }

        main .card {
            margin-bottom: 20px;
        }

        #r1 .card {
            height: 231px;
        }
        #r1_1 {
            margin-bottom: 0px;
        }

        .card {
            border-radius: 2%;
        }
        .card .content {
            border-radius: 2%;
        }
        .progress {
            /* background-color: #1D717E; */
            bottom: 0px;
            left: 0px;
            padding: 0px;
            margin: 0px;
            width: 100%;
            position: relative;
        }

        .progress .progress-bar {
            background-color: #1D717E;
            bottom: 0px;
            left: 0px;
            padding: 0px;
            margin: 0px;
            width: 100%;
        }

        .card-footer {
            /* background-color: #1D717E; */
            color: #fefafe;
            padding: 0px;
            margin: 0px;
            width: 100%;
            bottom: 0px;
            padding-bottom: 0%;
            margin-bottom: 0%;
            border-radius: 2%;
            border: 0%;
            position: relative;
        }
    </style>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>  
    <title>Dashboard</title>
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"> -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"> -->
    <!-- <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script> -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script> -->
    <!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script> -->
</head>
<body>
    <!-- <h1>Hello, world!</h1> -->

    <nav class="navbar navbar-dark fixed-top navbar-custom navbar-expand-lg flex-md-nowrap p-1 shadow p-1 mb-5 " >

        <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="{% url 'user:home' %}">Hi, {{ request.user.username }}!</a>
        <div class="navbar-collapse collapse flex-grow-1 text-right"> </div>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user:instructions' %}">Instructions</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user:logout' %}">Logout</a>
                </li>
            </ul>

    </nav>
    <main role="main">
        <div class="container" >
            <div class="row justify-content-center">
                <div class="col-5">
                    <div class="card shadow p-3 mb-5 bg-white rounded">
                        <div class="card-title">
                            <h3 >Stats</h3>
                        </div>
                        <div class="card-body">
                            <table class="table mx-auto">
                                <thead>
                                    <tr>
                                        <th scope="col">Stat</th>
                                        <th scope="col">Value</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>Total Participants</td>
                                        <td>{{ total_participants }}</td>
                                    </tr>
                                    <tr>
                                        <td>Session Completions Last Week</td>
                                        <td>{{ last_week }}</td>
                                    </tr>
                                    <tr>
                                        <td>Longitudinal Acceptance Rate<br>(of those who completed the first session)</td>
                                        <td>{{ long_acceptance_rate }}%</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="col-7">
                    <div class="card shadow p-3 mb-5 bg-white rounded">
                        <div class="card-title">
                            <h3 >Attrition Rates</h3>
                        </div>
                        <div class="card-body text-center">
                            <table class="table mx-auto">
                                <thead>
                                    <tr>
                                        <th scope="col">Session</th>
                                        <th scope="col">n</th>
                                        <th scope="col">Absolute%</th>
                                        <th scope="col">Relative%</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for session in sess_counts %}
                                    <tr>
                                        <td style="width: 10%;">{{ forloop.counter }}</td>
                                        <td style="width: 10%;">{{ session.0 }}</td>
                                        <td style="width: 40%;">
                                            <div class="progress mx-auto" style="width: 70%;">
                                                <div class="progress-bar" role="progressbar" style="width: {{session.1}}%;" aria-valuenow={{session.1}} aria-valuemin="0" aria-valuemax="100">{{session.1}}%</div>
                                            </div>
                                        </td>
                                        <td style="width: 40%;">
                                            <div class="progress mx-auto" style="width: 70%;">
                                                <div class="progress-bar" role="progressbar" style="width: {{session.2}}%;" aria-valuenow={{session.2}} aria-valuemin="0" aria-valuemax="100">{{session.2}}%</div>
                                            </div>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
</body>

{% include 'user/footer.html' %}

</html>

adminDash/templates/adminDash/login.html
<!DOCTYPE html>
<html lang="en" >
<head>
  <!-- <meta charset="UTF-8"> -->
  <meta name="viewport" content="width=device-width, initial-scale=1" charset="UTF-8">
  <title>Indian Mental Wellbeing Study: Welcome back! </title>
  {% load static %}  
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> 
  <link rel="stylesheet" href="{% static 'login.css' %}">
  <link rel="stylesheet" href="{% static 'footer.css' %}">
</head>

<body>
<!-- partial:index.partial.html -->
<section class='login' id='login'>
  <div class='head'>
  <h1 class='company'>Indian Mental Wellbeing Study</h1>
  </div>
  <p class='msg'>Welcome back!</p>
  <div class='form'>
    <form action="{% url 'adminDash:login' %}" method="post">
        {% csrf_token %}
        <input type="text" name="username" placeholder='Username' class='text' id='username' autofocus required><br>
        <input type="password" name="password" placeholder='••••••••••••••' class='password'><br>
        <!-- <a href="#" class='btn-login' id='do-login' type="submit">Login</a> -->
        <p style="color: #FF0000;">{% autoescape off %}{{ err_msg }}{% endautoescape %}
        </p>
        <div style="text-align:center;">
            <input class='btn-login' id='do-login' type="submit" value="Login"></input>
        </div>
        <br>
        <div>
          Forgot password? <a class='forgot' href="{% url 'user:reset' %}"> Reset password.</a> <br>
          Forgot username? <a class='forgot' href="{% url 'user:forgot_username' %}"> Get username.</a> <br>
          Don't have an account? <a class='forgot' href="{% url 'user:register' %}"> Register. </a>
        </div>
        <!-- <a href="#" class='forgot'>Forgot?</a> -->
    </form>
  </div>
</section>
<!-- partial -->

</body>
{% include 'user/footer.html' %}

</html>